FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt /app/requirements.txt

RUN echo "===== REQUIREMENTS.TXT IN IMAGE =====" && cat /app/requirements.txt && echo "====================================="

RUN python -m pip install --no-cache-dir -r /app/requirements.txt

RUN python -m pip show uvicorn

COPY app.py /app/app.py

EXPOSE 8010
CMD ["python", "-m", "uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8010"]